/**
 * Context Sync - generates AI agent context files from Redcon pack results.
 * Writes repo maps to .claude/redcon-context.md, .cursorrules, .github/copilot-instructions.md
 */

import * as fs from 'fs';
import * as path from 'path';
import type { RunReport, CompressedFileJson } from './types';

const MARKER = '<!-- redcon:auto-generated -->';

export type SyncTarget = 'claude' | 'cursor' | 'copilot';

export interface SyncResult {
  filesWritten: string[];
  filesSkipped: string[];
  errors: string[];
}

function groupByDir(files: { path: string }[]): Record<string, string[]> {
  const groups: Record<string, string[]> = {};
  for (const f of files) {
    const dir = f.path.split('/').slice(0, -1).join('/') || '.';
    if (!groups[dir]) groups[dir] = [];
    groups[dir].push(f.path.split('/').pop() ?? f.path);
  }
  return groups;
}

function describeFile(f: CompressedFileJson): string {
  const exports = f.symbols
    .filter((s) => s.exported)
    .slice(0, 8)
    .map((s) => `${s.kind} ${s.name}`)
    .join(', ');
  const saved = f.original_tokens > 0
    ? Math.round(((f.original_tokens - f.compressed_tokens) / f.original_tokens) * 100)
    : 0;
  const parts = [f.strategy.replace(/_/g, ' ')];
  if (saved > 0) parts.push(`${saved}% compressed`);
  if (exports) parts.push(`exports: ${exports}`);
  return parts.join(' | ');
}

export function generateContextMarkdown(run: RunReport, maxFiles: number = 30): string {
  const lines: string[] = [];

  lines.push(MARKER);
  lines.push(`# Redcon - Repository Context Map`);
  lines.push('');
  lines.push(`> Auto-generated by Redcon. Do not edit manually.`);
  lines.push(`> Task: ${run.task}`);
  lines.push(`> Generated: ${run.generated_at}`);
  lines.push(`> Budget: ${run.budget.estimated_input_tokens.toLocaleString()} / ${run.max_tokens.toLocaleString()} tokens (${Math.round((run.budget.estimated_input_tokens / run.max_tokens) * 100)}% used)`);
  lines.push('');

  // Section 1: Architecture overview
  const dirs = groupByDir(run.compressed_context);
  const dirEntries = Object.entries(dirs).sort((a, b) => b[1].length - a[1].length);

  lines.push('## Project Structure');
  lines.push('');
  lines.push('Key directories and their roles:');
  lines.push('');
  for (const [dir, files] of dirEntries.slice(0, 12)) {
    lines.push(`- \`${dir}/\` - ${files.length} files: ${files.slice(0, 5).join(', ')}${files.length > 5 ? ` (+${files.length - 5} more)` : ''}`);
  }
  lines.push('');

  // Section 2: Most important files
  const topRanked = run.ranked_files.slice(0, maxFiles);
  lines.push('## File Rankings');
  lines.push('');
  lines.push('Files ranked by relevance to the current task:');
  lines.push('');
  lines.push('| # | File | Score | Lines | Status |');
  lines.push('|---|------|-------|-------|--------|');
  for (let i = 0; i < topRanked.length; i++) {
    const f = topRanked[i];
    const included = run.files_included.includes(f.path);
    lines.push(`| ${i + 1} | \`${f.path}\` | ${f.score.toFixed(1)} | ${f.line_count} | ${included ? 'included' : 'skipped'} |`);
  }
  lines.push('');

  // Section 3: Included files with details
  lines.push('## Included Files');
  lines.push('');
  lines.push('Files packed into context with compression details:');
  lines.push('');
  for (const f of run.compressed_context) {
    const desc = describeFile(f);
    lines.push(`- \`${f.path}\` - ${desc}`);
  }
  lines.push('');

  // Section 4: Key symbols (exports)
  const allExports: { file: string; name: string; kind: string }[] = [];
  for (const f of run.compressed_context) {
    for (const s of f.symbols) {
      if (s.exported) {
        allExports.push({ file: f.path, name: s.name, kind: s.kind });
      }
    }
  }
  if (allExports.length > 0) {
    lines.push('## Key Exports');
    lines.push('');
    lines.push('Important symbols across the codebase:');
    lines.push('');
    for (const exp of allExports.slice(0, 40)) {
      lines.push(`- \`${exp.name}\` (${exp.kind}) in \`${exp.file}\``);
    }
    if (allExports.length > 40) {
      lines.push(`- ... and ${allExports.length - 40} more exports`);
    }
    lines.push('');
  }

  // Section 5: Skipped files summary
  if (run.files_skipped.length > 0) {
    lines.push('## Skipped Files');
    lines.push('');
    lines.push(`${run.files_skipped.length} files were excluded from context (low relevance or budget limit).`);
    if (run.files_skipped.length <= 20) {
      lines.push('');
      for (const f of run.files_skipped) {
        lines.push(`- \`${f}\``);
      }
    }
    lines.push('');
  }

  return lines.join('\n');
}

function wrapForClaude(markdown: string): string {
  return `${markdown}
---
*Use this map to understand which files are most relevant. Read the actual files when you need their contents.*
`;
}

function wrapForCursor(markdown: string, existing: string | null): string {
  // If existing .cursorrules has no redcon marker, prepend to it
  if (existing && !existing.includes(MARKER)) {
    return `${markdown}\n---\n\n${existing}`;
  }
  return markdown;
}

function wrapForCopilot(markdown: string): string {
  return `${markdown}
---
*This context map is auto-generated by Redcon. Consult the listed files for implementation details.*
`;
}

export async function syncContextFiles(
  run: RunReport,
  workspaceRoot: string,
  targets: SyncTarget[],
  maxFiles: number = 30,
): Promise<SyncResult> {
  const result: SyncResult = { filesWritten: [], filesSkipped: [], errors: [] };
  const markdown = generateContextMarkdown(run, maxFiles);

  for (const target of targets) {
    try {
      let filePath: string;
      let content: string;

      switch (target) {
        case 'claude': {
          const dir = path.join(workspaceRoot, '.claude');
          fs.mkdirSync(dir, { recursive: true });
          filePath = path.join(dir, 'redcon-context.md');
          content = wrapForClaude(markdown);
          break;
        }
        case 'cursor': {
          filePath = path.join(workspaceRoot, '.cursorrules');
          const existing = fs.existsSync(filePath)
            ? fs.readFileSync(filePath, 'utf-8')
            : null;
          // If existing file has our marker, replace entirely. Otherwise, prepend.
          if (existing && !existing.includes(MARKER)) {
            content = wrapForCursor(markdown, existing);
          } else {
            content = wrapForCursor(markdown, null);
          }
          break;
        }
        case 'copilot': {
          const dir = path.join(workspaceRoot, '.github');
          fs.mkdirSync(dir, { recursive: true });
          filePath = path.join(dir, 'copilot-instructions.md');
          content = wrapForCopilot(markdown);
          break;
        }
        default:
          continue;
      }

      fs.writeFileSync(filePath, content, 'utf-8');
      result.filesWritten.push(filePath);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      result.errors.push(`${target}: ${msg}`);
    }
  }

  return result;
}
